version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.31
    restart: always
    expose:
      - 4466
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
  model-server:
    build:
      context: ../model-server/
    expose:
      - 1111
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ../model-server/:/usr/app
      - /usr/app/node_modules
  front:
    build:
      context: ../front/
    depends_on:
      - prisma
      - model-server
    links:
      - prisma
      - model-server
    ports:
      - "3000:3000"
    volumes:
      - ../front/:/usr/app
      - /usr/app/node_modules
volumes:
  postgres: .
