version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.31
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
  plantuml-service:
    image: bitjourney/plantuml-service:1.3.5
    ports:
      - "1608:1608"
    restart: always
  model-front:
    build:
      context: ../model-front/
    depends_on:
      - model-server
    links:
      - model-server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    volumes:
      - ../model-front/:/usr/app
      - /usr/app/node_modules
  model-server:
    build:
      context: ../model-server/
    ports:
      - "1111:1111"
    depends_on:
      - plantuml-service
    links:
      - plantuml-service
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ../model-server/:/usr/app
      - /usr/app/node_modules
  app-server:
    build:
      context: ../app-server/
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ../app-server/:/usr/app
      - /usr/app/node_modules
  front:
    build:
      context: ../front/
    depends_on:
      - prisma
      - model-server
    links:
      - prisma
      - model-server
    ports:
      - "3000:3000"
    volumes:
      - ../front/:/usr/app
      - /usr/app/node_modules
volumes:
  postgres: ~

