version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.31
    restart: always
    links:
      - postgres
    depends_on:
      - postgres
    expose:
      - 4466
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
  postgres:
    image: postgres:10.3
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
  model-server:
    image: nielinjie/quickqui-model-server:latest
    expose:
      - 1111
    links:
      - prisma
    depends_on:
      - prisma
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  # TODO app-server image
  front:
    image: nielinjie/quickqui-front:latest
    depends_on:
      - prisma
      - model-server
    links:
      - prisma
      - model-server
    ports:
      - "3000:3000"
volumes:
  postgres: ~
