# TODO copy到阿里容器服务的“创建应用——采用编排模版“可以用。但直接用docker-compose在本地up会报错。
# nielinjies-Temp-bookPro:propotype nielinjie$ sh ./ali-up.sh 
# Creating network "propotype_default" with the default driver
# ERROR: The network driver must be specified.
#
#
version: '2'
services:
  prisma:
    image: prismagraphql/prisma:1.31
    restart: always
    depends_on:
      - postgres
    expose:
      - 4466
    links:
      - postgres
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
  postgres:
    image: postgres:10.3
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - 数据保存:/var/lib/postgresql
  model-server:
    image: nielinjie/quickqui-model-server:latest
    expose:
      - 1111
    links:
      - prisma
    depends_on:
      - prisma
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  # TODO 加入app-server 
  front:
    image: nielinjie/quickqui-front:latest
    depends_on:
      - prisma
      - model-server
    links:
      - prisma
      - model-server
    ports:
      - "3000:3000"
    labels:
      aliyun.routing.port_3000: front
