version: '3'
services:
  plantuml-service:
    image: bitjourney/plantuml-service:1.3.5
    ports:
      - "1608:1608"
    restart: always
  model-front:
    build:
      context: ../model-front/
    depends_on:
      - model-server
    links:
      - model-server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    volumes:
      - ../model-front/:/usr/app
      - /usr/app/node_modules
  model-server:
    build:
      context: ../model-server/
    ports:
      - "1111:1111"
    depends_on:
      - plantuml-service
    links:
      - plantuml-service
    environment:
      - NODE_ENV=development
      - ENV=dev_docker
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ../model-server/:/usr/app
      - /usr/app/node_modules
      - ./:/modelProjectDir

