infos:
  - name: config
    resources: ["Config"]
    scope: local
    type: resource
    init:
      Config:
        - id: _default
          #TODO 实现变量求值
          modelPath: ${env.MODEL_PATH}
          # memo需要每个字段都有。
          memo: "pass via env - MODEL_PATH, can not change while running"
    annotations:
      implementation:
        at: front
        source: storage
